# Generated by Django 5.2.1 on 2025-05-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('powerbank', 'Powerbank'), ('headphones', 'Headphones'), ('other_electronics', 'Other Electronics'), ('textbooks', 'Textbooks'), ('novels', 'Novels'), ('study_guides', 'Study Guides'), ('tutoring', 'Tutoring'), ('freelance', 'Freelance'), ('other_services', 'Other Services')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('exchange', 'Exchange')], max_length=20)),
                ('university', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.listing')),
            ],
        ),
    ]
